#!/usr/bin/env python3
"""Update the version in the manifest file."""

import json
import sys
from pathlib import Path

MANIFEST = "custom_components/template_media_player/manifest.json"


def main(version: str) -> None:
    with Path.open(MANIFEST) as file:
        data = json.load(file)

    data["version"] = version.replace("v", "")

    with Path.open(MANIFEST, "w") as file:
        json.dump(data, file, indent=2)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        version = sys.argv[1]
        main(version)
    else:
        print("Please provide a version argument.")
